version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - backend

  database:
    image: postgres:latest
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d/:ro
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
